from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
import json

db = SQLAlchemy()

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    
    # Relationships
    persona = db.relationship('Persona', backref='user', uselist=False, lazy=True)
    game_state = db.relationship('GameState', backref='user', uselist=False, lazy=True)
    puzzle_logs = db.relationship('PuzzleLog', backref='user', lazy=True)
    quiz_logs = db.relationship('QuizLog', backref='user', lazy=True)

    def __repr__(self):
        return f"User('{self.username}')"

class Persona(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    avatar_data = db.Column(db.JSON, nullable=False, default={}) # Stores: gender, hair, eyes, etc.
    
    def __repr__(self):
        return f"Persona('{self.name}', User: {self.user_id})"

class GameState(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    current_cycle = db.Column(db.Integer, default=1)
    current_step = db.Column(db.Integer, default=1) # 1-5 for puzzles, 6 for quiz
    completed_cycles = db.Column(db.Integer, default=0)
    last_updated = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"GameState(User: {self.user_id}, Cycle: {self.current_cycle}, Step: {self.current_step})"

class PuzzleLog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    cycle = db.Column(db.Integer, nullable=False)
    step = db.Column(db.Integer, nullable=False)
    puzzle_type = db.Column(db.String(50), nullable=False)
    puzzle_data = db.Column(db.JSON, nullable=False) # Parameters generated by AI
    solved = db.Column(db.Boolean, default=False)
    solved_at = db.Column(db.DateTime, nullable=True)

class QuizLog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    cycle = db.Column(db.Integer, nullable=False)
    questions = db.Column(db.JSON, nullable=False) # AI generated Quiz JSON
    score = db.Column(db.Integer, default=0)
    completed_at = db.Column(db.DateTime, default=datetime.utcnow)

class GateProgress(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    gate_number = db.Column(db.Integer, nullable=False) # 1-6
    status = db.Column(db.String(20), default='locked') # locked, unlocked, solved
    last_updated = db.Column(db.DateTime, default=datetime.utcnow)

class QuestionHistory(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    question_hash = db.Column(db.String(64), nullable=False) # Unique identifier/hash of the question
    topic = db.Column(db.String(50))
    is_correct = db.Column(db.Boolean, default=False)
    attempted_at = db.Column(db.DateTime, default=datetime.utcnow)
